### PR TITLE
chore: migrate from page router -> Nextjs App router

### PR DESCRIPTION
**Pull request by NawinKumarSharma**
changes: 
image

image

### CODE REVIEW

**Comment by NawinKumarSharma** [comment]
this solves #335 @animemoeus

**Review by animemoeus — CHANGES_REQUESTED** [review]
Hmm, have you tested on your local?

Seems like the site is broken. Hahaha

image

**Comment by NawinKumarSharma** [comment]
@animemoeus can you check once more? its working from my side . 
image

**Comment by NawinKumarSharma** [comment]
@animemoeus , hey completed with changes. now it is working smooth. here is the demo, can you review it now?

[Screencast from 2024-10-04 21-53-23.webm](https://github.com/user-attachments/assets/f8b92b7f-8e40-49aa-ad7b-f26d05a4fdc7)

**Review by animemoeus — CHANGES_REQUESTED** [review]
@NawinKumarSharma one minor changes and should be ok 👍 😁 

image

**Comment by NawinKumarSharma** [comment]
@animemoeus done with the changes!

[Screencast from 2024-10-05 19-58-18.webm](https://github.com/user-attachments/assets/2276dd40-bf47-493f-90a9-e3b23d5d9c31)

**Review by animemoeus — APPROVED** [review]

**Comment by animemoeus** [comment]
LGTM! 👍

**Pull request merged**
